package(default_visibility = ["//visibility:public"])

cc_test(
    name = "bytecode_breakpoint_test",
    srcs = ["bytecode_breakpoint_test.cc"],
    deps = [
        "//src/googleclouddebugger:bytecode_breakpoint",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "bytecode_manipulator_test",
    srcs = ["bytecode_manipulator_test.cc"],
    deps = [
        "//src/googleclouddebugger:bytecode_manipulator",
        "@com_google_googletest//:gtest_main",
    ],
)
